### ISSUE TITLE
Minecraft Could not pass event EntityDamageByEntityEvent to FNAmplifications

### ISSUE THREAD

**Issue by jefflima1** [FN-FAL113/FN-FAL-s-Amplifications#120]
- [Mon 14:44:35 ERROR Minecraft] Could not pass event EntityDamageByEntityEvent to FNAmplifications vDev - 102
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer cannot be cast to class org.bukkit.entity.Arrow (org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer and org.bukkit.entity.Arrow are in unnamed module of loader java.net.URLClassLoader @3d82c5f3)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.MysteryStick6.onSwing(MysteryStick6.java:64)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.listener.MysteryStickListener.onEntityDamage(MysteryStickListener.java:73)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor696.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289)
    at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2223)
    at net.minecraft.world.entity.player.Player.damageEntity0(Player.jav

Paper git-Paper-318 (MC: 1.20.2)
Slimefun Dev - 1135
Metrics-Module #29
Java 17
Installed Addons: (21)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  Networks vDEV - 50 (git 3de3c9d6)
  AureliumSkills vBeta 1.3.24
  FastMachines vDev - 8
  RelicsOfCthonia vDev - 12
  FoxyMachines vDEV - 67 (git 0028aa93)
  FNAmplifications vDev - 102
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  DynaTech vMain - 5
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  SlimeHUD vDev - 1
  Supreme vDEV - 29 (git f9e70053)
  LiteXpansion vMODIFIED
  SimpleUtils vDEV - 15 (git 4250fd5e)
  SFMobDrops vDev - 6
  RedProtect v8.1.1-SNAPSHOT
  ExtraHeads vDev - 26
  SoulJars vDEV - 24 (git 78d1c6fa)
  MobCapturer vDev - 34
  FluffyMachines vDev - 4

**Comment by FN-FAL113** [comment]
How do I reproduxe this, can you share more info how you got this exception

**Comment by FN-FAL113** [comment]
fixed, going to test it first before shipping a new update.

**Comment by jefflima1** [comment]
This error happens sometimes, I don't know exactly what causes this to happen, I don't see it often, as many players do, I only detected it in the logs, but sorry, I'll try to monitor it better to understand this.

**Comment by jefflima1** [comment]
- [Tue 14:37:11 ERROR Minecraft] Could not pass event EntityDamageByEntityEvent to FNAmplifications vDev - 102
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer cannot be cast to class org.bukkit.entity.Arrow (org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer and org.bukkit.entity.Arrow are in unnamed module of loader java.net.URLClassLoader @3d82c5f3)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.MysteryStick6.onSwing(MysteryStick6.java:64)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.listener.MysteryStickListener.onEntityDamage(MysteryStickListener.java:73)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor697.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289)
    at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2223)
    at net.minecraft.world.entity.player.Player.damageEntity0(Player.jav

- [Tue 14:37:17 ERROR Minecraft] Could not pass event EntityDamageByEntityEvent to FNAmplifications vDev - 102
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer cannot be cast to class org.bukkit.entity.Arrow (org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer and org.bukkit.entity.Arrow are in unnamed module of loader java.net.URLClassLoader @3d82c5f3)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.MysteryStick6.onSwing(MysteryStick6.java:64)
    at FNAmplifications.jar//ne.fnfal113.fnamplifications.mysteriousitems.listener.MysteryStickListener.onEntityDamage(MysteryStickListener.java:73)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor697.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054)
    at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289)
    at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2223)
    at net.minecraft.world.entity.player.Player.damageEntity0(Player.jav

**Comment by jefflima1** [comment]
It's getting more and more frequent, I don't know what could be causing this.

**Comment by FN-FAL113** [comment]
Typed this on my phone, I'll test out the fix when I get to have time, maybe today but can't promise I'm on a time constraint unfortunately.

**Comment by FN-FAL113** [comment]
Resolved on latest push, give the project a star if you like the addon :).
