### ISSUE TITLE
cant enable

### ISSUE THREAD

**Issue by lucasGithuber** [FN-FAL113/FN-FAL-s-Amplifications#3]
got an error when trying to enable the addon
```Error occurred while enabling FNAmplifications v2.4-MatGenRecipe (Is it up to date?)

java.lang.NoClassDefFoundError: dev/j3fftw/litexpansion/extrautils/interfaces/InventoryBlock

at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]

at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]

at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[patched_1.17.1.jar:git-Paper-359]

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-359]

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

at ne.fnfal113.fnamplifications.Items.FNAmpItemSetup.registerPowerGens(FNAmpItemSetup.java:39) ~[FNAmplifications.v2.4-MatGenRecipe.jar:?]

at ne.fnfal113.fnamplifications.Items.FNAmpItemSetup.init(FNAmpItemSetup.java:27) ~[FNAmplifications.v2.4-MatGenRecipe.jar:?]

at ne.fnfal113.fnamplifications.FNAmplifications.onEnable(FNAmplifications.java:26) ~[FNAmplifications.v2.4-MatGenRecipe.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-359]

at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-359]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-359]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-359]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-359]

at java.lang.Thread.run(Unknown Source) ~[?:?]

Caused by: java.lang.ClassNotFoundException: dev.j3fftw.litexpansion.extrautils.interfaces.InventoryBlock

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-359]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-359]

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

... 21 more```

**Comment by FN-FAL113** [comment]
Thank you for reporting, will be fixed in the next version
