### ISSUE TITLE
Tri-sword invisible armor stands don't go away until chunk is released after update to version 65.

### ISSUE THREAD

**Issue by cybermancerr** [FN-FAL113/FN-FAL-s-Amplifications#75]
Tri-sword invisible armor stands don't go away until chunk is released:

https://cdn.discordapp.com/attachments/624966637816381440/965150427404435496/unknown.png
https://cdn.discordapp.com/attachments/624966637816381440/965151738816524348/unknown.png
https://cdn.discordapp.com/attachments/624966637816381440/965152203637674034/unknown.png

Errors thrown in console when bug executes:

ERROR21:56:43
Could not pass event PlayerInteractEvent to FNAmplifications vDEV - 65 (git 5e572d87)
Console21:56:43
java.lang.IllegalArgumentException: `The found tag instance cannot store String as it is a NBTTagByte
at org.bukkit.craftbukkit.v1_18_R2.persistence.CraftPersistentDataTypeRegistry.extract(CraftPersistentDataTypeRegistry.java:254) ~[paper-1.18.2.jar:git-Paper-271]
at org.bukkit.craftbukkit.v1_18_R2.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:67) ~[paper-1.18.2.jar:git-Paper-271]
at org.bukkit.craftbukkit.v1_18_R2.persistence.CraftPersistentDataContainer.getOrDefault(CraftPersistentDataContainer.java:72) ~[paper-1.18.2.jar:git-Paper-271]
at ne.fnfal113.fnamplifications.gems.TriSwordGem.onRightClick(TriSwordGem.java:65) ~[FN-FAL-s-Amplifications - DEV 54 (git b26bd).jar:?]
at ne.fnfal113.fnamplifications.gems.listener.GemListener.lambda$onClick$6(GemListener.java:227) ~[FN-FAL-s-Amplifications - DEV 54 (git b26bd).jar:?]
at ne.fnfal113.fnamplifications.gems.listener.GemListener.callGemHandler(GemListener.java:69) ~[FN-FAL-s-Amplifications - DEV 54 (git b26bd).jar:?]
at ne.fnfal113.fnamplifications.gems.listener.GemListener.onClick(GemListener.java:227) ~[FN-FAL-s-Amplifications - DEV 54 (git b26bd).jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1034.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-271]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-271]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.18.2.jar:git-Paper-271]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.18.2.jar:git-Paper-271]
at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1909) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-271]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
21:56:44
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-271]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-271]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by FN-FAL113** [comment]
Will take a look at this :)

**Comment by FN-FAL113** [comment]
Sorry for the inconvenience

**Comment by FN-FAL113** [comment]
what do you mean by chunks released, what are the steps needed to reproduce this
